services:
  nginx:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - flask-backend

  flask-backend:
    build: ./backend
    # volumes:
      # - /home/harry/data/config:/home/harry/data/config
    environment:
      - ROOT_DIR=/home/harry/data/config
      - SECRET_KEY=secretkey2026
    expose:
      - "8000"
