services:
  nginx:
    build: .
    volumes:
      - /home/harry/data:/app/data
    ports:
      - "8080:80"
    depends_on:
      - flask-backend

  flask-backend:
    build: ./backend
    volumes:
      - /home/harry/data:/app/data
    environment:
      - ROOT_DIR=/app/data
      - SECRET_KEY=secretkey2026
    expose:
      - "8000"
